language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot

matrix:
  allow_failures:
    -
      php: 7.1
    -
      php: 7.4snapshot

git:
  depth: 1

branches:
  only:
    - master

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

install:
  - composer self-update
  - git config --global github.accesstoken $GITHUB_OAUTH_TOKEN
  - composer install

script:
  - vendor/bin/phpunit --coverage-text=coverage.txt
  - vendor/bin/phpcs --report-summary --report-gitblame .

after_script:
  - head coverage.txt
